-- MySQL Script generated by MySQL Workbench
-- Fri Feb 22 00:52:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE TABLE Contrato (
  `numContrato` INT NOT NULL,
  `Objeto_contrato` VARCHAR(45) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `num_ano` INT NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `documentos` MEDIUMBLOB ,
  `links` VARCHAR(100) ,
  PRIMARY KEY (`numContrato`),
  UNIQUE INDEX `numContrato_UNIQUE` (`numContrato` ASC))
ENGINE = InnoDB;


CREATE TABLE Participante (
  `idParticipante` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `matricula` INT UNSIGNED NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(10) NOT NULL,
  `setor` VARCHAR(45) ,
  `cargo` VARCHAR(45) ,
  `funcao` VARCHAR(45) ,
  `tipo` VARCHAR(45) ,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParticipante`))
ENGINE = InnoDB;

CREATE TABLE Contrato_has_Participante (
  `Contrato_numContrato` INT NOT NULL,
  `Participante_idParticipante` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Contrato_numContrato`, `Participante_idParticipante`),
  INDEX `fk_Contrato_has_Participante_Participante1_idx` (`Participante_idParticipante`) ,
  INDEX `fk_Contrato_has_Participante_Contrato_idx` (`Contrato_numContrato`) ,
  CONSTRAINT `fk_Contrato_has_Participante_Contrato`
    FOREIGN KEY (`Contrato_numContrato`)
    REFERENCES `Contrato` (`numContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_has_Participante_Participante1`
    FOREIGN KEY (`Participante_idParticipante`)
    REFERENCES `Participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
