-- MySQL Script generated by MySQL Workbench
-- Wed Feb  6 21:54:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`Contrato` (
  `numContrato` INT NOT NULL,
  `Objeto_contrato` VARCHAR(45) NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `num_ano` INT NOT NULL,
  `modalidade` VARCHAR(45) NULL,
  PRIMARY KEY (`numContrato`),
  UNIQUE INDEX `numContrato_UNIQUE` (`numContrato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`Participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`Participante` (
  `idParticipante` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NULL,
  `matricula` INT UNSIGNED NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(10) NULL,
  `setor` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `funcao` VARCHAR(45) NULL,
  `email` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `login` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `tipoUsuario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idParticipante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`Contrato_Participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`Contrato_Participante` (
  `Contrato_numContrato` INT NOT NULL,
  `Participante_idParticipante` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Contrato_numContrato`, `Participante_idParticipante`),
  INDEX `fk_Contrato_has_Participante_Participante1_idx` (`Participante_idParticipante` ASC) VISIBLE,
  INDEX `fk_Contrato_has_Participante_Contrato_idx` (`Contrato_numContrato` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_has_Participante_Contrato`
    FOREIGN KEY (`Contrato_numContrato`)
    REFERENCES `tcc`.`Contrato` (`numContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_has_Participante_Participante1`
    FOREIGN KEY (`Participante_idParticipante`)
    REFERENCES `tcc`.`Participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
